FROM python:3.10-buster

ENV PYTHONUNBUFFERED 1

COPY . /app

WORKDIR /app

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

EXPOSE 8000

CMD ["uvicorn", "todo:app", "--host", "0.0.0.0", "--port", "8000"]